language: "perl"
perl:
  - "5.20"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install postgresql
  - cpanm -q --notest install Sparrow

install:
  - sparrow index update
  - sparrow plg install postgresql-check

script:
  - sparrow plg run postgresql-check
